jdbc:
  driver: org.postgresql.Driver
  url: jdbc:postgres://${jdbc.host}:${jdbc.port}?${jdbc.options}
  username: postgres
  password: postgres
  port: 5432

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
