on:
  port: 8888
  address: 0.0.0.0

admin:
  port: 0
  address: 0.0.0.0

app:
  domain: ''
  brand: App
  search: false
  navbar: true
  fluid: false
  cdn: auto # in DEV mode is false, in PRODUCTION is true
  home: /
  menu: {}
  sectors:
    admin:
      brand: '<i class="fa fa-dashboard"></i> Admin'
      home: /_
      menu:
        Overview: /_
        Routes: /_routes
        Config: /_config
        Metrics: /_metrics
        JMX:
          Memory pool: /_jmx/mempool
          JVM Threads: /_jmx/threads
          Operating system: /_jmx/os
          Garbage collection: /_jmx/gc
          Memory: /_jmx/memory
          Runtime: /_jmx/runtime
          Classes: /_jmx/classes
          Compilation: /_jmx/compilation

users: {}

jobs:
  executor:
    threads: 64
  scheduler:
    threads: 64

hibernate:
  c3p0:
    min_size: 5
    max_size: 100
    timeout: 300
    max_statements: 50
    idle_test_period: 100

oauth:
  google:
    clientId: YOUR_GOOGLE_CLIENT_ID_HERE
    clientSecret: YOUR_GOOGLE_CLIENT_SECRET_HERE

  github:
    clientId: YOUR_GITHUB_CLIENT_ID_HERE
    clientSecret: YOUR_GITHUB_CLIENT_SECRET_HERE

  facebook:
    clientId: YOUR_FACEBOOK_CLIENT_ID_HERE
    clientSecret: YOUR_FACEBOOK_CLIENT_SECRET_HERE

  linkedin:
    clientId: YOUR_LINKEDIN_CLIENT_ID_HERE
    clientSecret: YOUR_LINKEDIN_CLIENT_SECRET_HERE
