jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306
  username: root
  password: root

gui:
  title: The Constants
  brand: The Constants
  search: false
  fluid: false
  menu:
    Constants: /
    API (right):
      Pi: /pi
      G: /g
    Help:
      About: /about

api:
  /pi: select 3.14 as Pi
  /g: select 9.81 as G

pages:
  /: select 3.14 as Pi, 9.81 as G
  /about: ''
